seed: 123
trainsteps: 10000
demosteps: 10000
env: "MountainCar-v0"
policy: "MlpPolicy"
method: 1
plot: 1 # enable = 1, disable = 0
plot_update_interval: 1000
reset_heat_map_every_plot: true
n_milestones: 10
policy_kwargs:
  net_arch: [ 64,64 ]
uncertainty_kwargs:
  scale: 1
  state_bounds: null
  resolution: 25
  first_n_dim: 1
