seed: 123
trainsteps: 100000
demosteps: 10
env: "MountainCar-v0"
policy: "MlpPolicy"
method: 1
plot: 1 # enable = 1, disable = 0
policy_kwargs:
  net_arch: [ 64,64 ]
uncertainty_kwargs:
  scale: 1
  state_bounds: null
  resolution: 5
  first_n_dim: 2
